services:
  api:
    build:
      context: .
      target: production
    container_name: caveo-api-prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # AWS credentials will be provided by EC2 IAM role
      - AWS_REGION=${AWS_REGION:-us-east-1}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - caveo-network

networks:
  caveo-network:
    driver: bridge
    name: caveo-production
