version: '3.8'

services:
  postgres:
    container_name: my_postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caveo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: